### ISSUE TITLE
Support jacoco.xml sourcefiles that don't have branches information 

### ISSUE THREAD

**Issue by eduramiba** [vokal/jacoco-parse#5]
For example [this file](https://github.com/uniform-java/uniform/blob/master/src/main/java/net/uniform/html/renderers/HiddenRenderer.java) produces:

```xml
    <class name="net/uniform/html/renderers/HiddenRenderer">
      <method desc="()V" line="31" name="&lt;init&gt;">
        <counter covered="3" missed="0" type="INSTRUCTION"/>
        <counter covered="1" missed="0" type="LINE"/>
        <counter covered="1" missed="0" type="COMPLEXITY"/>
        <counter covered="1" missed="0" type="METHOD"/>
      </method>
      <method desc="(Lnet/uniform/html/elements/Hidden;)Ljava/util/List;" line="35" name="render">
        <counter covered="35" missed="0" type="INSTRUCTION"/>
        <counter covered="8" missed="0" type="LINE"/>
        <counter covered="1" missed="0" type="COMPLEXITY"/>
        <counter covered="1" missed="0" type="METHOD"/>
      </method>
      <counter covered="38" missed="0" type="INSTRUCTION"/>
      <counter covered="9" missed="0" type="LINE"/>
      <counter covered="2" missed="0" type="COMPLEXITY"/>
      <counter covered="2" missed="0" type="METHOD"/>
      <counter covered="1" missed="0" type="CLASS"/>
    </class>
```

The produced exception is:

```nodejs
Uncaught TypeError: Cannot read property '$' of undefined
      at node_modules/jacoco-parse/source/index.js:68:44
      at Array.map (native)
      at node_modules/jacoco-parse/source/index.js:23:35
      at Array.forEach (native)
      at unpackage (node_modules/jacoco-parse/source/index.js:21:14)
      at node_modules/jacoco-parse/source/index.js:114:22
      at Parser.<anonymous> (node_modules/xml2js/lib/xml2js.js:489:18)
      at Object.onclosetag (node_modules/xml2js/lib/xml2js.js:447:26)
      at emit (node_modules/sax/lib/sax.js:640:35)
      at emitNode (node_modules/sax/lib/sax.js:645:5)
      at closeTag (node_modules/sax/lib/sax.js:905:7)
      at Object.write (node_modules/sax/lib/sax.js:1452:13)
      at Parser.exports.Parser.Parser.parseString (node_modules/xml2js/lib/xml2js.js:508:31)
      at Parser.parseString (node_modules/xml2js/lib/xml2js.js:7:59)
      at exports.parseString (node_modules/xml2js/lib/xml2js.js:540:19)
      at Object.parse.parseContent (node_modules/jacoco-parse/source/index.js:107:5)
      at node_modules/jacoco-parse/source/index.js:129:15
      at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by eduramiba** [comment]
See #6
